accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name="detail"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies_index, name='movies_index'),
    path('<int:movie_pk>/', views.movies_detail, name='movies_detail'),
    path('<int:movie_pk>/reviews/new/', views.review_create, name='review_create'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/like/', views.like, name='like')
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)
    

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    genres = models.ManyToManyField(Genre)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_movies")



class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', )

movies/forms.py
from django import forms

from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'score')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
# Create your views here.
def index(request):
    context = {
        'users' : get_user_model().objects.all()
    }
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            auth_login(request, form.save())
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def detail(request, user_pk):
    context = {
        'user_profile' : get_user_model().objects.get(pk=user_pk)
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

@login_required
def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user != user:
        if user in request.user.followers.all():
            request.user.followers.remove(user)
        else:
            request.user.followers.add(user)
    return redirect('accounts:detail', user_pk)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Genre, Movie, Review
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm
# from django.contrib import messages

# Create your views here.
def movies_index(request):
    movies = Movie.objects.all()
    context = {
        'movies' : movies
    }
    return render(request, 'movies/movies_index.html', context)

def movies_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    form = ReviewForm()
    context = {
        'movie': movie,
        'form': form
    }
    return render(request, 'movies/movies_detail.html', context)

@require_POST
def review_create(request, movie_pk):
    if request.user.is_authenticated:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.movie_id = movie_pk
            review.save()
    else:
        messages.warning(request, '로그인이 필요합니다.')
    return redirect('movies:movies_detail', movie_pk)


def review_delete(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    review.delete()
    messages.warning(request, '리뷰가 삭제되었습니다.')
    return redirect('movies:movies_detail', movie_pk)

@require_POST
def like(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user.is_authenticated:
        if movie in request.user.like_movies.all():
            request.user.like_movies.remove(movie)
        else:
            request.user.like_movies.add(movie)
    else:
        messages.warning(request, '로그인이 필요한 기능입니다.')
    return redirect('movies:movies_detail', movie_pk)

accounts/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'movies:movies_index' %}">MovieBuddy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <!-- <a class="nav-link" href="{% url 'movies:movies_index' %}">Home <span class="sr-only">(current)</span></a> -->
            </li>
            <!-- 로그인이 되어 있다면, -->
            {% if user.is_authenticated %} <!-- 로그인이 되어 있는지 확인하는 method -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:detail' user.pk%}"> {{user.username}}</a> <!-- login과 관련된 모든 정보는 request에 저장되어 있기 때문에 context로 안넘겨줘도 사용 가능! -->
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}"> 로그아웃</a>
            </li>
            <!-- 로그인이 되어 있지 않다면, -->
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}"> 회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}"> 로그인</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>로그인 페이지</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% block css %}{% endblock %}
  
</head>
<body>
    {% include '_navbar.html' %}
  <div class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{% if message.tags %}{{ message.tags}}{% endif %}">
  {{ message }}
  </div>
  {% endfor %}
  {% endif %}
    {% block body %}
    {% endblock %}
  </div>
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
</body>
</html>

accounts/templates/accounts/detail.html
{% extends 'accounts/base.html' %}
{% block body %}
    <h1>{{ user_profile.username }}님의 프로필</h1>
    <hr>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:follow' user_profile.pk %}">
            <button>
                {% if user in user_profile.followings.all %}Un{% endif %}Follow
            </button>
        </a>
    {% endif %}
    <br>
    {{ user_profile.followings.count }}명이 좋아합니다.
    {{ user_profile.followers.count }}명을 좋아합니다.

    <h3>{{ user_profile.username }}님이 작성한 평점 정보</h3>
    <ul>
        {% for review in user_profile.review_set.all %}
            <li><a href="{% url 'movies:detail' review.movie.pk %}">{{ review.movie.title }}</a>: {{ review.score }}점
            <a href="{% url 'movies:update_score' review.pk %}">
                <button>수정하기</button>
            </a>
            </li>
        {% empty %}
            <li>작성한 평점이 없습니다.</li>
        {% endfor %}
    </ul>
    <br>
    <h3>{{ user_profile.username }}님이 좋아하는 영화 정보</h3>
    <ul>
        {% for movie in user_profile.like_movies.all %}
            <li><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a> ({{ movie.genre.name }})</li>
        {% empty %}
            <li>좋아하는 영화가 없습니다.</li>
        {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'accounts/base.html'%}
{% load bootstrap4 %}

{% block body %}
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">submit</button>
  {% endbuttons %}
</form>
{% endblock %}

accounts/templates/accounts/index.html
  
{% extends 'accounts/base.html' %}
{% load bootstrap4 %}

{% block body %}
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">User</th>
        <th scope="col">Follower</th>
        <th scope="col">Following</th>
      </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
        <th scope="row">{{ user.id }}</th>
        <td>
        <a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a>
        </td>
        <td>{{ user.followings.count }}</td>
        <td>{{ user.followers.count }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
<!-- <table>
    <thead>
        <tr>
            <th>id</th>
            <th>username</th>
            <th>email</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.pk }}</td>
                <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
            </tr>
        {% empty %}
            <tr>
                <td>회원이 존재하지 않습니다.</td>
            </tr>
        {% endfor %}
    </tbody>
</table> -->
{% endblock %}

movies/templates/movies/detail.html
{% extends 'accounts/base.html' %}
{% block body %}

<img src="{{ movie.poster_url }}" alt="{{ movie.title }}" style="width:20vw;">
<h3>제목: {{ movie.title }}</h3>
<hr>
<p>관객수: {{ movie.audience }}명</p>
<p>장르: {{ movie.genre.name }}</p>
<p>줄거리: {{ movie.description }}</p>

{% if user.is_authenticated %}
    <form action="{% url 'movies:like' movie.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">좋아요
        {% if movie in user.like_movies.all %}
        취소
        {% endif %}
        ({{ movie.like_users.count }})
        </button>
    </form>
{% endif %}

{% for review in movie.review_set.all %}
    <p><a href="{% url 'accounts:detail' review.user.pk %}">{{ review.user.username }}</a>: {{ review.content }} ({{ review.score }}점)</p>
    <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="POST" onclick="return confirm('삭제하시겠습니까?')">
        {% csrf_token %}
        <button type="submit">삭제</button>
    </form>
{% empty %}
    <p>등록된 평점이 없습니다.</p>
{% endfor %}

{% if user.is_authenticated %}
    <form action="{% url 'movies:review_create' movie.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">확인</button>
    </form>
{% endif %}
{% endblock %}

movies/templates/movies/index.html
{% extends 'accounts/base.html' %}

{% block body %}
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.pk %}">
            <img src="{{ movie.poster_url }}" alt="{{ movie.title }}" style="width:20vw;">
        </a>
    {% empty %}
        <p>등록된 영화가 없습니다.</p>
    {% endfor %}
{% endblock %}

movies/templates/movies/movies_detail.html
{% extends 'accounts/base.html' %}
{% block body %}

<img src="{{ movie.poster_url }}" alt="{{ movie.title }}" style="width:20vw;">
<h3>제목: {{ movie.title }}</h3>
<hr>
<p>관객수: {{ movie.audience }}명</p>
<p>장르: {{ movie.genre.name }}</p>
<p>줄거리: {{ movie.description }}</p>

{% if user.is_authenticated %}
    <form action="{% url 'movies:like' movie.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">좋아요
        {% if movie in user.like_movies.all %}
        취소
        {% endif %}
        ({{ movie.like_users.count }})
        </button>
    </form>
{% endif %}

{% for review in movie.review_set.all %}
    <p><a hef="{% url 'accounts:detail' review.user.pk %}">{{ review.user.username }}</a>: {{ review.content }} ({{ review.score }}점)</p>
    <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="POST" onclick="return confirm('삭제하시겠습니까?')">
        {% csrf_token %}
        <button type="submit">삭제</button>
    </form>
{% empty %}
    <p>등록된 평점이 없습니다.</p>
{% endfor %}

{% if user.is_authenticated %}
    <form action="{% url 'movies:review_create' movie.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">확인</button>
    </form>
{% endif %}
{% endblock %}

movies/templates/movies/movies_index.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block body %}
    <img src="{% static 'movies/background2.jpg' %}" alt ="" height = 200 width=97%>
    {% for movie in movies %}
        <a href="{% url 'movies:movies_detail' movie.pk %}">
            <img src="{{ movie.poster_url }}" alt="{{ movie.title }}" style="width:24%;">
        </a>
    {% empty %}
        <p>등록된 영화가 없습니다.</p>
    {% endfor %}
{% endblock %}